[package]
name = "tikv_connect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tikv-client = "0.3"
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
