[package]
name = "config_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
config = "0.14.0"
serde="1.0.196"
serde_json="1.0.113"